platform :ios, '9.0'

target 'ankelny' do
  # Firebase
  rn_path = '../node_modules/react-native'
  
  
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  # react-native-maps d ependencies
  # pod 'Firebase/Core', '~> 5.3.0'
  # pod 'Firebase/Messaging', '~> 5.3.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'react-native-image-picker' , :path => '../node_modules/react-native-image-picker'
  pod 'RNI18n' , :path=> '../node_modules/react-native-i18n'
  pod 'ReactNativeLocalization', :path=>'../node_modules/react-native-localization'
end