import LocalizedStrings from "react-native-localization";
import { Header } from "react-native-elements";
export default localization = new LocalizedStrings({
    en: {
        home: 'Home',
        menu: 'Menu',
        search: 'Search',
        cart: 'cart',
        settings: 'Settings',
        add:'add',
        userName:'User Name',
        headerSignin:'Signin',
        headerSigninDriver:'Driver Signin',
        selectCategory:'Select Category',
        imageFormat:'Image Format',
        imageID:'Image ID',
        License:'License',
        from:'From',
        to:'To',
        date:'Date',
        driverName:'Driver Name',
        termsAndConditions:'Terms And Conditions',
        oK:'OK',
        callUs:'Call Us',
        name:'Name',
        phoneNumber:'Telephone Number',
        message:'Message',
        rechargeTheBalance:'Recharge the Balance',
        Balance:'Balance',
        CodeNumber:'Enter code number',
        shipping:'Charge',
        notifications:'Notifications',
        myRequests:'My Requests',
        exit:'Exit',
        newOrdersDriver:'new Orders',
        newOrdersClient:'new Orders',
        source:'Source',
        dis:'Distination',
        expectedPayment:'Expected Cost',
        refuse:'Refuse',
        accept:'Accept',
        cancel:'Cancel',
        sentSucces:'sent successfully',
        willBeNotified:'you will be notified when accepted',
        next:'Next',
        approximate:'Approximate',
        send:'Send',
        changePassword:'Change Password',
        signin:'login',
        forgetPassword:'Forget Password?',
        headerSigninClient:'Client Signin',
        address:'Address',
        signup:'signup',
        call:'call'



    },
    ar: {
        home: 'الرئيسية',
        menu: 'القائمة',
        search: 'البحث',
        cart: 'العربة',
        settings: 'الإعدادات',
        add:'أضف',
        userName:'اسم المستخدم',
        headerSignin:'تسجيل الدخول',
        headerSigninDriver:'تسجيل السائق',
        headerSigninClient:'تسجيل العميل',
        selectCategory:'اختر الفئه',
        imageFormat:'صوره الاستماره',
        imageID:'صوره الهويه',
        License:'الرخصه',
        from:'مـــــــــــــن',
        to:'إلـــــــــــــي',
        date:'التــاريـــــخ',
        driverName:'اسم السائق',
        termsAndConditions:'الشروط والاحكام',
        oK:'موافق',
        callUs:'اتصل بنا',
        name:'الاسم',
        phoneNumber:'رقم الهاتف',
        message:'الرساله',
        rechargeTheBalance:'شحن رصيد',
        Balance:'شحن',
        CodeNumber:'ادخل رقم الكود',
        shipping:'شحن',
        notifications:'الاشعارات',
        myRequests:'طلباتي',
        exit:'خروج',
        newOrdersDriver:'طلبات جديدة',
        newOrdersClient:'طلبات جديدة',
        source:'الاقلاع',
        dis:'الوصول',
        expectedPayment:'القيمه التقديرية',
        refuse:'رفض',
        accept:'قبول',
        cancel:'إلغء',
        sentSucces:'تم ارسال طلبك بنجاح',
        willBeNotified:'سوف يتم اشعارك عند القبول',
        next:'التالي',
        approximate:'السعر التقريبي',
        send:'ارسال',
        changePassword:'إستعاده كلمة المرور',
        signin:'دخول',
        forgetPassword:'نسيت كلمة المرور؟',
        address:'العنوان',
        signup:'تسجيل',
        call:'اتصال'

    }
})
